---

- name: Ensure Tomcat is running
  service:
    name: tomcat
    state: started
    enabled: yes

- name: Stop Tomcat server
  service:
    name: tomcat
    state: stopped

- name: Pull artifact from Nexus
  get_url:
    url: "{{ nexus_url }}/com/dept/app/MyWebApp/1.0/MyWebApp-1.0.war"
    dest: "/tmp/MyWebApp-1.0.war"
    validate_certs: yes

- name: Validate downloaded artifact
  command: "sha256sum /tmp/MyWebApp-1.0.war"
  register: artifact_checksum
  failed_when: artifact_checksum.rc != 0

- name: Log artifact checksum
  command: "echo '{{ artifact_checksum.stdout }}' >> /var/log/artifact_checksums.log"
  when: artifact_checksum.rc == 0
  register: checksum_logged
  failed_when: checksum_logged.rc != 0

- name: Deploy application to Tomcat webapps
  copy:
    src: "/tmp/MyWebApp-1.0.war"
    dest: "{{ tomcat_deploy_path }}/MyWebApp-1.0.war"
    remote_src: true
    become: true

- name: Start Tomcat server
  service:
    name: tomcat
    state: started

