---
- name: Ensure sha256sum is installed
  become: yes
  yum:
    name: sha256sum
    state: present
  when: "'sha256sum' not in ansible_facts['os_family']"

- name: Ensure Tomcat is running
  service:
    name: tomcat
    state: started
    enabled: yes

- name: Stop Tomcat server
  service:
    name: tomcat
    state: stopped

- name: Pull artifact from Nexus
  get_url:
    url: "{{ nexus_url }}/repository/java-docker-nexus-release/com/dept/app/MyWebApp/1.0/MyWebApp-1.0.war"
    dest: "/tmp/MyWebApp-1.0.war"

- name: Validate downloaded artifact
  command: "sha256sum /tmp/MyWebApp-1.0.war"
  register: artifact_checksum
  failed_when: artifact_checksum.rc != 0

- name: Log artifact checksum
  ansible.builtin.command: "echo '{{ artifact_checksum.stdout | quote }}' >> /tmp/artifact_checksums.log"
  when: artifact_checksum.rc == 0

- name: Deploy application to Tomcat webapps
  copy:
    src: "/tmp/MyWebApp-1.0.war"
    dest: "{{ tomcat_deploy_path }}/MyWebApp-1.0.war"
    remote_src: true
  become: true

- name: Start Tomcat server
  service:
    name: tomcat
    state: started

