---
- name: Deploy application to Tomcat server
  hosts: tomcat-host
  become: true
  remote_user: jenkins
  roles: 
    - deploy

  vars:
     nexus_url: "http://nexus.example.com"
     tomcat_deploy_path: "/var/lib/tomcat/webapps"    

